import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';

const UPLOADS_DIR = path.join(process.cwd(), 'uploads');

if (!fs.existsSync(UPLOADS_DIR)) {
  fs.mkdirSync(UPLOADS_DIR, { recursive: true });
}

interface FormData {
  landlordName?: string;
  tenantName?: string;
  propertyAddress?: string;
  monthlyRent?: string;
  securityDeposit?: string;
  tenurePeriod?: string;
  startDate?: string;
  city?: string;
  state?: string;
  [key: string]: string | undefined;
}

function formatDate(dateStr?: string): string {
  if (!dateStr) return 'N/A';
  try {
    return new Date(dateStr).toLocaleDateString('en-IN', {
      day: 'numeric',
      month: 'long',
      year: 'numeric',
    });
  } catch {
    return dateStr;
  }
}

function drawPageBorderAndHeader(doc: PDFKit.PDFDocument, docType: string) {
  // Draw premium border
  doc.rect(30, 30, 552, 732).lineWidth(2).stroke('#1a365d'); // Outer thick border
  doc.rect(34, 34, 544, 724).lineWidth(0.5).stroke('#1a365d'); // Inner thin border

  // Header: Company Logo / Name
  doc.font('Helvetica-Bold').fontSize(24).fillColor('#1a365d').text('NyayAI', { align: 'center' });
  doc.font('Helvetica').fontSize(10).fillColor('#718096').text('Premium Legal Documentation Services', { align: 'center' });
  doc.moveDown(1);

  // Document Title
  const title = docType.toUpperCase().replace(/-/g, ' ');
  doc.font('Helvetica-Bold').fontSize(18).fillColor('#2d3748').text(title, { align: 'center', underline: true });
  doc.moveDown(0.5);
  doc.font('Helvetica').fontSize(10).fillColor('#4a5568').text(`Execution Date: ${new Date().toLocaleDateString('en-IN')}`, { align: 'center' });
  
  // Reset text color for body
  doc.fillColor('#000000').moveDown(2);
}

export async function generatePdf(
  docType: string,
  formData: FormData,
  docId: string
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 60, size: 'A4' });
    const chunks: Buffer[] = [];
    
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    drawPageBorderAndHeader(doc, docType);

    switch (docType) {
      case 'rent-agreement':
        buildRentAgreement(doc, formData);
        break;
      default:
        buildGenericDocument(doc, docType, formData);
    }

    // Footer
    doc.fontSize(8).fillColor('#a0aec0').text(
      'This document is digitally generated by NyayAI and does not require a physical signature for system validation.',
      50,
      760,
      { align: 'center', width: 512 }
    );

    doc.end();
  });
}

function buildRentAgreement(doc: PDFKit.PDFDocument, f: FormData) {
  const line = (label: string, value: string) => {
    doc.font('Helvetica-Bold').fontSize(11).text(`${label}: `, { continued: true });
    doc.font('Helvetica').text(value || 'N/A');
    doc.moveDown(0.4);
  };

  doc.font('Helvetica').fontSize(11).text(
    `This Rent Agreement is made and entered into on this date, ${formatDate(f.startDate)}, between the following parties, subject to the terms and conditions outlined below.`,
    { align: 'justify', lineGap: 4 }
  );
  doc.moveDown(1.5);

  doc.rect(50, doc.y, 512, 1).fill('#e2e8f0'); // Divider
  doc.moveDown(1);

  doc.fontSize(14).font('Helvetica-Bold').fillColor('#1a365d').text('I. PARTIES TO THE AGREEMENT');
  doc.moveDown(0.5);
  doc.fillColor('#000000');
  line('Landlord Name', f.landlordName || '');
  line('Tenant Name', f.tenantName || '');
  doc.moveDown();

  doc.fontSize(14).font('Helvetica-Bold').fillColor('#1a365d').text('II. PROPERTY DETAILS');
  doc.moveDown(0.5);
  doc.fillColor('#000000');
  line('Property Address', f.propertyAddress || '');
  line('City', f.city || '');
  line('State', f.state || '');
  doc.moveDown();

  doc.fontSize(14).font('Helvetica-Bold').fillColor('#1a365d').text('III. COMMERCIAL TERMS');
  doc.moveDown(0.5);
  doc.fillColor('#000000');
  line('Monthly Rent', `₹${f.monthlyRent || '0'} (Indian Rupees)`);
  line('Security Deposit', `₹${f.securityDeposit || '0'} (Indian Rupees)`);
  line('Tenure Period', `${f.tenurePeriod || '0'} months`);
  line('Commencement Date', formatDate(f.startDate));
  doc.moveDown(1.5);

  doc.rect(50, doc.y, 512, 1).fill('#e2e8f0'); // Divider
  doc.moveDown(1);

  doc.font('Helvetica-Oblique').fontSize(10).text(
    'By signing below, both parties acknowledge and agree to the terms stipulated in this agreement in accordance with the Indian Contract Act, 1872.',
    { align: 'justify', lineGap: 3 }
  );
  doc.moveDown(4);

  doc.font('Helvetica-Bold').fontSize(12);
  doc.text('_______________________', 60, doc.y, { continued: false });
  doc.text('_______________________', 350, doc.y - 14);
  doc.moveDown(0.5);
  doc.font('Helvetica').fontSize(10);
  doc.text('Signature of Landlord', 60, doc.y);
  doc.text('Signature of Tenant', 350, doc.y - 12);
}

function buildGenericDocument(
  doc: PDFKit.PDFDocument,
  docType: string,
  formData: FormData
) {
  doc.fontSize(11).font('Helvetica');
  Object.entries(formData).forEach(([key, value]) => {
    if (value) {
      const label = key.replace(/([A-Z])/g, ' $1').replace(/^./, (s) => s.toUpperCase());
      doc.font('Helvetica-Bold').fillColor('#2d3748').text(`${label}: `, { continued: true });
      doc.font('Helvetica').fillColor('#000000').text(value);
      doc.moveDown(0.6);
    }
  });
  doc.moveDown(2);
  doc.fontSize(10).font('Helvetica-Oblique').text(
    `This ${docType.replace(/-/g, ' ')} has been drafted by the NyayAI platform based on the user's inputs. It is subject to applicable Indian laws and should be reviewed by legal counsel if necessary.`,
    { align: 'justify' }
  );
}
